/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: balls.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "balls.pb-c.h"
void   ball_draw_display_msg__init
                     (BallDrawDisplayMsg         *message)
{
  static const BallDrawDisplayMsg init_value = BALL_DRAW_DISPLAY_MSG__INIT;
  *message = init_value;
}
size_t ball_draw_display_msg__get_packed_size
                     (const BallDrawDisplayMsg *message)
{
  assert(message->base.descriptor == &ball_draw_display_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ball_draw_display_msg__pack
                     (const BallDrawDisplayMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ball_draw_display_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ball_draw_display_msg__pack_to_buffer
                     (const BallDrawDisplayMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ball_draw_display_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BallDrawDisplayMsg *
       ball_draw_display_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BallDrawDisplayMsg *)
     protobuf_c_message_unpack (&ball_draw_display_msg__descriptor,
                                allocator, len, data);
}
void   ball_draw_display_msg__free_unpacked
                     (BallDrawDisplayMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ball_draw_display_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ball_draw_display_msg__field_descriptors[3] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BallDrawDisplayMsg, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BallDrawDisplayMsg, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BallDrawDisplayMsg, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ball_draw_display_msg__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange ball_draw_display_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ball_draw_display_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ball_draw_display_msg",
  "BallDrawDisplayMsg",
  "BallDrawDisplayMsg",
  "",
  sizeof(BallDrawDisplayMsg),
  3,
  ball_draw_display_msg__field_descriptors,
  ball_draw_display_msg__field_indices_by_name,
  1,  ball_draw_display_msg__number_ranges,
  (ProtobufCMessageInit) ball_draw_display_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
